### PR TITLE
Add query builder tests

### PR DESCRIPTION
**Pull request by mcse3010**
# Purpose

I was having trouble with the SearchQueryBuilder between() function, and did not understand how it worked, so I went looking for unit tests, and didn't find any, so I wrote unit tests for each of the query builders to get a better understanding.  I also plan on adding a SortQueryBuilder to add sorting functionality, with tests and documentation

# Related Material

N/A

# Remarks

I tried to revert inadvertently changing yarn.lock, and it appears to be the same, but is still flagged as a remove/add line... not sure why.

I also had updated the tsconfig to es2016 during the process (trying to resolve a red herring), but it turned out unnecessary 
 and so I reverted to es6.

### CODE REVIEW

**Comment by amcintosh** [comment]
Hi!
Thanks for this! 

We actually do have tests for these [here](https://github.com/freshbooks/freshbooks-nodejs-sdk/blob/main/packages/api/__tests__/Builders.test.ts), but the tests are not organized so I can see how you would miss them. I think I will merge your work in, remove any duplicate tests from the existing, and migrate anything missing over to your files so that they are more findable in the future. 

Also for the future the usage is documented [here](https://freshbooks.github.io/freshbooks-nodejs-sdk/pages/guide/custom_queries.html#search-filters) but we're happy to work on that if it's unclear.

Thanks again!

**Comment by mcse3010** [comment]
I think because the docs didn’t say explicitly min or max, that’s why my queries were not being rendered.  It’s obvious in the code, not from the docs, it just says RangeType and that doesn’t seem to appear in the docs, unless i missed that too.  Thanks for the consideration.  Is there a sort query builder that I missed as well?
________________________________

**Comment by amcintosh** [comment]
That is a good point, I don't believe the examples have the explicit min or max. I'll look to adding those.
And you are correct, the docs don't feature the sort at all, nor do the tests.

Thanks for pointing this out!

**Comment by mcse3010** [comment]
I will try to add sort this week along with tests and documentation.  Where should the sort builder tests live?  The builder would be under model though right?
________________________________

**Comment by amcintosh** [comment]
Thanks!
Yes, I would say to put the builder under /models/builders. 
The tests can live alongside the ones you've already written. I'll get them merged in and do any refactoring of our existing test separately.

**Comment by amcintosh** [comment]
Hi @mcse3010. I've created an issue for the sort query: https://github.com/freshbooks/freshbooks-nodejs-sdk/issues/1008

**Comment by mcse3010** [comment]
Very nice!  Thanks! I will be sure to add it soon
________________________________

**Pull request merged**
